topo:
  rawfile: swissALTI3D_merged.tif
  file: &topofile bathymetry_with_dam.asc
  lake_alt: 1767
  dam_alt: 1780
  resolution: 5

  bounds:
    xmin: 2666500.
    xmax: 2673700.
    ymin: 1169500.
    ymax: 1174200.

  flood_seed: [2.67026e+6, 1.171490e+6]

AVAC:
  nx: 100
  ny: 100
  nsim: 10
  tmax: 90
  dt0: 1.
  cfl: 0.5
  max_iter: 500
  DryWetLimit: 0.0001
  out_format: binary

  amr_ratios:
    x: [4, 4, 8]
    y: [4, 4, 8]
    t: [4, 4, 8]
    max_level: 3

  topo:
    - [2, *topofile]
  qinit:
    - [qinit.xyz]

TSUL:
  nx: 20
  ny: 32

  bounds:
    xmin: 2669750.
    xmax: 2671000.
    ymin: 1170200.
    ymax: 1172160.

  amr_ratios:
    x: [2, 2]
    y: [2, 2]
    t: [2, 2]
    max_level: 3

  topo:
    - [2, *topofile]
  qinit:
    - [qinit.xyz]
  out_format: binary
