TOPM:
  topography: swissALTI3D_merged.tif
  bathymetry: &topofile TOPM/bathymetry.asc
  avalanches: avalanches.geojson
  lake_alt: 1767
  dam_alt: 1780
  resolution: 5

  bounds:
    xmin: 2666500.
    xmax: 2673700.
    ymin: 1169500.
    ymax: 1174200.

  flood_seed: [2.67026e+6, 1.171490e+6]

AVAC:
  avalanches: TOPM/avalanches.csv
  nx: 30
  ny: 20
  nsim: 10
  tmax: 90
  dt0: 1.
  cfl: 0.5
  max_iter: 500
  dry_tolerance: 0.0001
  out_format: binary

  amr_ratios:
    x: [2, 4, 8]
    y: [2, 4, 8]
    t: [2, 4, 8]
    max_level: 3
  cells_max: 60

  topo: *topofile

TSUL:
  nx: 30
  ny: 40

  bounds:
    xmin: 2669650.
    xmax: 2671000.
    ymin: 1170100.
    ymax: 1172260.

  amr_ratios:
    x: [4, 4, 4]
    y: [4, 4, 4]
    t: [4, 4, 4]
    max_level: 3
  cells_max: 100


  topo: *topofile
  qinit: TSUL/qinit.xyz
  out_format: binary

  inflow: "src"  # "bc" or "src"
