TOPM:
  topography: swissALTI3D_merged.tif
  bathymetry: &topofile TOPM/bathymetry.asc
  avalanches: avalanches.geojson
  lake_alt: 1767
  dam_alt: 1771.2
  resolution: 3
  smooth_radius: 4

  overhang: 20

  bounds:
    xmin: 2666500.
    xmax: 2673700.
    ymin: 1169500.
    ymax: 1174200.

  flood_seed: [2.6705e+6, 1.1710e+6]

AVAC:
  friction: friction.csv
  out_format: binary

  topo: *topofile

TSUL:
  bounds:
    xmin: 2669650.
    xmax: 2671000.
    ymin: 1170100.
    ymax: 1172260.

  topo: *topofile
  out_format: binary

  inflow: "src"  # "bc" or "src"
